[env]
CONFIG_PATH = './src/config/development.yaml'

[tools]
deno = "latest"

[tasks.up]
run = ['limactl start default', 'docker compose up -d']

[tasks.down]
run = ['docker compose down', 'limactl stop default']

[tasks.test-load]
run = 'k6 run ./test/k6/load-test.js'

[tasks.ci]
run = [
  'deno check .',
  'deno task migrate down --to 0',
  'deno task migrate up',
  'deno test',
]
